name: Download and Run Notebook from Colab

on: 
  push :
  
  workflow_dispatch :

jobs:
  download-and-run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: ServiceAccountCredentials
      run: |
        python --version 
        python -m pip --version
        python -m pip install earthengine-api --upgrade
        python -c "import ee" 

    - run: |
        python -c "import ee; 
        json = ${{ secrets.JSON }}
        credentials = ee.ServiceAccountCredentials(${{ secrets.SERVICE_ACCOUNT }}, json)
        ee.Initialize(credentials);
        print(ee.String('Hello from the Earth Engine servers!').getInfo()); "


    - name: Download Notebook from Colab
      run: |
        curl -L -o notebook.ipynb "https://drive.google.com/uc?export=download&id=1nepMvRGwKPaO6BgmBhzCEcIphLIqsF1w"

    - name: Install Jupyter
      run: |
        pip install notebook nbconvert

    - name: Run Notebook
      run: |
          jupyter nbconvert --to notebook --execute notebook.ipynb --output executed_notebook.ipynb

    - name: Upload executed notebook
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebook
        path: executed_notebook.ipynb


