name: Download and Run Notebook from Colab

on: 
  push :
  
  workflow_dispatch :

jobs:
  download-and-run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download Notebook from Colab
      run: |
        curl -L -o notebook.ipynb "YOUR_COLAB_NOTEBOOK_URL"

    - name: Install Jupyter
      run: |
        pip install notebook nbconvert

    - name: Run Notebook
      run: |
        curl -L -o notebook.ipynb "https://drive.google.com/uc?export=download&id=1nepMvRGwKPaO6BgmBhzCEcIphLIqsF1w"

    - name: Upload executed notebook
      uses: actions/upload-artifact@v2
      with:
        name: executed-notebook
        path: executed_notebook.ipynb


