name: "notebook_2"

on: 
  workflow_dispatch :

  push :
    paths: 
      Population 
      
permissions:
  pages: write
  contents: read
  id-token: write

concurrency:
  group: "workflow-group-${{ github.ref }}" 
  cancel-in-progress: true 


jobs:
  download-and-run-notebook:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        python --version 
        python -m pip --version

    - run: |
        python -m pip install earthengine-api --upgrade --quiet 
        python -c "import ee" 

    - run: |
        python -m pip install geemap    
        python -c "import geemap"

    - run: |
        ## settings/secrets/actions 
        ## important!!  
        ## When configuring the json data, exchange " for \" 
        echo "${{ secrets.JSON }}" > credentials.json
        
        python Population/earth_tools.py
        ls -la 
        more output.json 




