name: Download and Run Notebook from Colab

on: 
  push :
  
  workflow_dispatch :

jobs:
  download-and-run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        python --version 
        python -m pip --version

    - run: |
        python -m pip install earthengine-api --upgrade --quiet 
        python -c "import ee" 

    - run: |
        python -m pip install geemap    
        python -c "import geemap"

    - name : Authentification1 
      run: |
        ## settings/secrets/actions 
        ## important!! replace 
        ## When configuring the json data, exchange " for \" 
        echo "${{ secrets.JSON }}" > credentials.json
        
        echo "import sys; 
        import ee
        from google.oauth2 import service_account
        
        service_account_key_file = 'credentials.json'        
        credentials = service_account.Credentials.from_service_account_file(
            service_account_key_file,
            scopes=['https://www.googleapis.com/auth/earthengine',
                    'https://www.googleapis.com/auth/cloud-platform']
        )        
        ee.Initialize(credentials)
        print(ee.String('Hello from the Earth Engine servers!').getInfo()); " > script.py 
        python script.py ${{ secrets.SERVICE_ACCOUNT }}


    - name : Authentification2 
      run: |
        ## settings/secrets/actions 
        ## important!! replace 
        ## When configuring the json data, exchange " for \" 
        echo "${{ secrets.JSON }}" > credentials.json
        
        echo "import sys; 
        import ee; 
        credentials = ee.ServiceAccountCredentials(sys.argv[1], 'credentials.json')
        ee.Initialize(credentials);
        print(ee.String('Hello from the Earth Engine servers!').getInfo()); " > script.py 

        python script.py ${{ secrets.SERVICE_ACCOUNT }}

    - name: Download Notebook from Colab
      run: |
        curl -L -o notebook.ipynb "https://drive.google.com/uc?export=download&id=1nepMvRGwKPaO6BgmBhzCEcIphLIqsF1w"

    - name: Install Jupyter
      run: |
        pip install notebook nbconvert --quiet 

    - name: Run Notebook
      run: |
          SERVICE_ACCOUNT="${{ secrets.SERVICE_ACCOUNT }}" jupyter nbconvert --to notebook --execute notebook.ipynb --output executed_notebook.ipynb

    - name: Upload executed notebook
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebook
        path: executed_notebook.ipynb


