name: "notebook_2"

on: 
  workflow_dispatch :

  #push :
  #  paths: 
  #    - 'Jsons/conflict.geojson'
      
permissions:
  pages: write
  contents: write
  id-token: write


concurrency:
  group: "workflow-group-${{ github.ref }}" 
  cancel-in-progress: true 


jobs:
  download-and-run-notebook:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout 
      uses: actions/checkout@v4

    - env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run : | 
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        echo "${{ github.actor }}" 
        gh auth status
        git commit --allow-empty -m "This is an empty commit"
        #git push origin main
        git push https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        python --version 
        python -m pip --version
        
    - run: |
        python -m pip install earthengine-api --upgrade --quiet 
        python -c "import ee" 
        
    - run: |
        python -m pip install geemap    
        python -c "import geemap"
        
    - run: |
        ## settings/secrets/actions 
        ## important!!  
        ## When configuring the json data, exchange " for \" 
        echo "${{ secrets.JSON }}" > credentials.json
        
        python Population/earth_tools.py
        mv output.json Population/population.json
        find . 
        
    - run: |
        git add Population/population.json
        git commit --allow-empty -m "output.json updated"
        git push origin main
          
