name: simplest_workflow_dispatch

on:
  workflow_dispatch:

concurrency:
  group: "workflow-group-${{ github.ref }}" 
  cancel-in-progress: true 

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a simple script
        run: echo "Hello, world!"


