name: simplest_workflow_dispatch

on:
  workflow_dispatch:

concurrency:
  group: "workflow-group-${{ github.ref }}" 
  cancel-in-progress: true 

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        
      - name: Run a simple script
        run: |
          echo "Hello, world!"
          mkdir Dummies
          dd if=/dev/zero of=Dummies/dummy1.txt bs=1M count=10
          #mv dummy0.txt Dummies/dummy1.txt

      - name: Upload map
        uses: actions/upload-artifact@v4
        with:
          name: population
          path: Dummies/dummy1.txt


