name: simplest_workflow_dispatch

on:
  workflow_dispatch:

concurrency:
  group: "workflow-group-${{ github.ref }}" 
  cancel-in-progress: true 

jobs:
  dummy_job :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        
      - name: Creating dummies
        run: |
          mkdir Dummies
          dd if=/dev/zero of=Dummies/artifact_1.txt bs=1M count=10

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_name 
          path: Dummies/artifact_1.txt


