name: to_pages

on:
  push:
    branches:
      - main  
    paths:
      - docs/* 
      
  workflow_dispatch : 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./path-to-output-folder
          #destination_branch: gh-pages


